image: python:3.7.3

options:
  max-time: 10

pipelines:
  branches:
    master:
      - step:
          max-time: 10
          script:
            - pipe: atlassian/ssh-run:0.2.6
              variables:
                SSH_USER: 'deploy'
                SERVER: 'stage.task-focus'
                MODE: 'command'
                COMMAND: 'cd /home/deploy/project_management_api && git pull && /home/deploy/project_management_api/venv/bin/pip install -r requirements.txt && /home/deploy/project_management_api/venv/bin/python manage.py migrate && /home/deploy/project_management_api/venv/bin/python manage.py collectstatic --noinput && sudo service project_management_api restart'
