# Generated by Django 4.1.4 on 2022-12-23 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_team_members_remove_team_owner_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="log",
            old_name="description",
            new_name="message",
        ),
    ]
