# Generated by Django 4.1.4 on 2023-03-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_description_log_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="eta_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="ProjectAttribute",
        ),
    ]
