# Generated by Django 4.1.7 on 2023-04-03 14:50

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_task_eta_date_delete_projectattribute"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="log",
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="TaskWorkSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("stopped_at", models.DateTimeField(auto_now_add=True)),
                ("total_time", models.IntegerField(default=0)),
                ("message", models.TextField()),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_work",
                        to="core.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_work",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
