# Generated by Django 4.1.7 on 2023-04-04 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_log_options_taskworksession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="progress",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
