# Generated by Django 4.1.7 on 2023-04-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_notification_notificationack'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tag',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
