# Generated by Django 4.1.7 on 2023-05-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_taskchecklistitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="estimated_work_hours",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="is_urgent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="position",
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OPEN", "OPEN"),
                    ("IN PROGRESS", "IN PROGRESS"),
                    ("BLOCKER", "BLOCKER"),
                    ("TO VERIFY", "TO VERIFY"),
                    ("DONE", "DONE"),
                    ("ON_HOLD", "ON_HOLD"),
                ],
                max_length=150,
                null=True,
            ),
        ),
    ]
