# Generated by Django 4.1.7 on 2023-06-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_remove_user_nametag"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
