# Generated by Django 4.1.7 on 2023-08-04 08:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_team_teamuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TeamUser",
        ),
    ]
