# Generated by Django 4.1.7 on 2023-08-15 11:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_project_progress_project_tag_alter_task_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reminder",
            options={"ordering": ["reminder_date"]},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["username"]},
        ),
    ]
