# Generated by Django 4.1.7 on 2023-08-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_alter_reminder_options_alter_user_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="archived_at",
        ),
        migrations.AddField(
            model_name="project",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
    ]
