# Generated by Django 4.1.7 on 2023-08-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_remove_project_archived_at_project_is_closed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pushover_user",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="taskworksession",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
