# Generated by Django 4.1.7 on 2023-08-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_user_pushover_user_alter_taskworksession_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notifier_user",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
