# Generated by Django 4.1.7 on 2023-11-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_user_notifier_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="blocks",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
