# Generated by Django 4.1.7 on 2023-11-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_task_blocks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="blocks",
            field=models.JSONField(default=dict),
        ),
    ]
