# Generated by Django 4.1.7 on 2024-05-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_private_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="urgency_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TODAY", "TODAY"),
                    ("TOMORROW", "TOMORROW"),
                    ("IN 3 DAYS", "IN 3 DAYS"),
                    ("WEEK_PLUS", "WEEK PLUS"),
                ],
                max_length=150,
                null=True,
            ),
        ),
    ]
