# Generated by Django 4.1.7 on 2024-08-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_task_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskblock",
            name="content",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
