# Generated by Django 4.1.7 on 2024-09-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_task_block_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="follow_up",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
