# Generated by Django 4.1.7 on 2024-09-15 20:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_task_block_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
