# Generated by Django 4.1.7 on 2024-11-18 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_commentreaction_commentack_reaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="board",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="core.board",
            ),
        ),
    ]
