# Generated by Django 4.1.7 on 2024-11-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_board_in_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="card",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="carditem",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
