# Generated by Django 4.1.7 on 2024-12-01 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_board_configs"),
    ]

    operations = [
        migrations.AddField(
            model_name="pin",
            name="board",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pinned_boards",
                to="core.board",
            ),
        ),
    ]
