# Generated by Django 4.1.7 on 2024-12-03 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_pin_board"),
    ]

    operations = [
        migrations.AddField(
            model_name="carditem",
            name="board",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card_items_pointing_to_board",
                to="core.board",
            ),
        ),
    ]
