# Generated by Django 4.1.7 on 2025-03-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_card_item_board_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltaskblock",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="taskblock",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
