# Generated by Django 4.1.7 on 2025-02-07 13:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_card_item_board_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Beacon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="beacon",
            constraint=models.UniqueConstraint(
                condition=models.Q(("confirmed_at__isnull", True)),
                fields=("user",),
                name="unique_unconfirmed_beacon_per_user",
            ),
        ),
    ]
