# Generated by Django 4.1.7 on 2025-03-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_beacon_beacon_unique_unconfirmed_beacon_per_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltaskblock",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="taskblock",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
