# Generated by Django 5.1.7 on 2025-04-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_task_block_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="use_beacons",
            field=models.BooleanField(default=False),
        ),
    ]
